# Imports

### Libraries

In [1]:
%matplotlib inline
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
from glob import glob
import json
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import matplotlib.dates as dates_
import seaborn as sns
from pyowm.owm import OWM
from pyowm.utils import timestamps, formatting
from datetime import datetime, timedelta, timezone, date

### Data

##### Split dataframes into dictionaries by day

In [79]:
def df_by_day(df, date_col_name="start_time"):
    # Get all available days
    days = df[date_col_name].dt.to_period("D").unique()

    #create a DataFrame dictionary to store your data frames
    df_by_day = {elem : pd.DataFrame for elem in days}

    for key in df_by_day.keys():
        df_by_day[key] = df[:][df[date_col_name].dt.to_period("D") == key]
    
    return df_by_day, days

##### Heart Beat Data

In [10]:
# Find all json files
samsung_base_dir = os.path.join('data', 'Samsung Data', '04.12.2021')

json_file_names = []
for file in os.listdir(os.path.join(samsung_base_dir, 'jsons', 'com.samsung.health.heart_rate')):
    if file != '.ipynb_checkpoints':
        json_file_names.append(file)

df_json_readings = []
for i in range(len(json_file_names)):
    file_name = json_file_names[i]
    df = pd.read_json(os.path.join(samsung_base_dir,'jsons', 'com.samsung.health.heart_rate', file_name))
    df_json_readings.append(df.copy())

df_heart_rate_json = pd.concat(df_json_readings, axis=0, ignore_index=True)
df_heart_rate_json = df_heart_rate_json.sort_values(by=['start_time'], ascending=True, ignore_index=True)

###### Create dictionnary with data per day

In [26]:
HR_by_day, HR_day_keys = df_by_day(df_heart_rate_json)

In [27]:
HR_by_day[HR_day_keys[0]]

,heart_rate,heart_rate_max,heart_rate_min,start_time,end_time
0,80,82,79,2021-11-28 12:40:00,2021-11-28 12:40:59
1,83,87,78,2021-11-28 12:41:00,2021-11-28 12:41:59
2,82,85,80,2021-11-28 12:42:00,2021-11-28 12:42:59
3,83,86,80,2021-11-28 12:43:00,2021-11-28 12:43:59
4,80,82,77,2021-11-28 12:44:00,2021-11-28 12:44:59
...,...,...,...,...,...
538,68,74,63,2021-11-28 22:36:00,2021-11-28 22:36:59
539,75,78,72,2021-11-28 22:37:00,2021-11-28 22:37:59
540,77,90,72,2021-11-28 22:38:00,2021-11-28 22:38:59
541,94,97,89,2021-11-28 22:39:00,2021-11-28 22:39:59
542,87,90,86,2021-11-28 22:40:00,2021-11-28 22:40:59

##### Calendar Data

In [17]:
# Load CSV file
cal_base_dir = os.path.join('data', 'Calendar Data')
df_calendar = pd.read_csv(os.path.join('data', 'Calendar Data', '05.12.2021.csv'), sep='\t')

# Rename columns with simpler names
df_calendar = df_calendar.rename(columns={'Given planned earliest start' : 'start_time', 'Given planned earliest end' : 'end_time'})
df_calendar = df_calendar.drop(['Notes', 'Assigned Resources', 'Additional Title'], axis=1)

# Convert date columns into date format
df_calendar['start_time'] = pd.to_datetime(df_calendar['start_time'], dayfirst=True)
df_calendar['end_time'] = pd.to_datetime(df_calendar['end_time'], dayfirst=True)

# Sort Dataframe by date
df_calendar = df_calendar.sort_values(by=['start_time'], ascending=True, ignore_index=True)

In [82]:
cal_by_day, cal_day_keys = df_by_day(df_calendar)

##### Weather Data
We can go back up to 5 days ago, but unfortunately not more than that.

In [51]:
APIKEY = '12c406b33039d61c116a70eefb3526bb' #your API Key here as string
OpenWMap = OWM(APIKEY) # Use API key to get data
mgr = OpenWMap.weather_manager()
lausanne_lat = 46.5196535
lausanne_lon = 6.6322734

# Query current data
observation_cur = mgr.weather_at_place('Lausanne') # give where you need to see the weather
weather_cur = observation_cur.weather

# Query yesterday data
yesterday_epoch = formatting.to_UNIXtime(timestamps.yesterday())
one_call_yesterday = mgr.one_call_history(lat=lausanne_lat, lon=lausanne_lon, dt=yesterday_epoch)
weather_yesterday = one_call_yesterday.forecast_hourly

# Query 4 days ago data
nb_of_days = 1
three_days_ago_epoch = int((datetime.now() - timedelta(days=nb_of_days)).replace(tzinfo=timezone.utc).timestamp())
one_call_four_days_ago = mgr.one_call_history(lat=52.5244, lon=13.4105, dt=three_days_ago_epoch)
weather_four_days_ago = one_call_four_days_ago.forecast_hourly

In [52]:
# Iterate over each hour of the day
for i in range(len(weather_four_days_ago)):
    print(weather_four_days_ago[i].detailed_status)
    print(weather_four_days_ago[i].temperature('celsius'))

light snow
{'temp': 1.19, 'feels_like': -3.85}
light snow
{'temp': 1.45, 'feels_like': -3.73}
light rain
{'temp': 1.45, 'feels_like': -3.93}
light rain
{'temp': 0.94, 'feels_like': -3.29}
overcast clouds
{'temp': 1.01, 'feels_like': -2.93}
light intensity drizzle
{'temp': 1.71, 'feels_like': -2.2}
light snow
{'temp': 1.64, 'feels_like': -1.98}
light snow
{'temp': 1.56, 'feels_like': -2.66}
broken clouds
{'temp': 1.68, 'feels_like': -1.93}
broken clouds
{'temp': 1.68, 'feels_like': -1.93}
overcast clouds
{'temp': 1.44, 'feels_like': -1.74}
broken clouds
{'temp': 2.21, 'feels_like': -1.86}
broken clouds
{'temp': 2.33, 'feels_like': -1.71}
broken clouds
{'temp': 2.62, 'feels_like': -0.46}
overcast clouds
{'temp': 2.49, 'feels_like': -0.61}
overcast clouds
{'temp': 2.3, 'feels_like': -1.18}
overcast clouds
{'temp': 2.17, 'feels_like': -1.63}
overcast clouds
{'temp': 1.87, 'feels_like': -1.7}
broken clouds
{'temp': 1.76, 'feels_like': -2.67}
broken clouds
{'temp': 1.84, 'feels_like': -2.04}
broken clouds
{'temp': 1.76, 'feels_like': -2.9}
broken clouds
{'temp': 1.42, 'feels_like': -3.33}
broken clouds
{'temp': 1.52, 'feels_like': -2.43}
light snow
{'temp': 1.33, 'feels_like': -2.66}

##### Step Count Data

In [77]:
# Find all json files
samsung_base_dir = os.path.join('data', 'Samsung Data', '04.12.2021')

# Finding step count file
filename = ''
for file in os.listdir(samsung_base_dir):
    if file.startswith('com.samsung.health.step_count'):
        filename = file


# Importing data
cols_names = ["speed", "pkg_name", "count", "sample_position_type", "time_offset", "start_time", "calorie", 
              "deviceuuid", "custom", "end_time", "datauuid", "distance", "create_time", "update_time"]
df_step_count = pd.read_csv(os.path.join(samsung_base_dir, filename), skiprows=1,names=cols_names)

# Cleaning dataset
cols_to_drop = ["pkg_name", "sample_position_type", "time_offset", "deviceuuid", "custom", "datauuid", "create_time", "update_time"]
df_step_count = df_step_count[1:]
df_step_count = df_step_count.drop(cols_to_drop, axis=1)

# Convert date columns into date format
df_step_count['start_time'] = df_step_count['start_time'].replace('Ã ', 'at', regex=True)

df_step_count['end_time'] = df_step_count['start_time'].replace('Ã ', 'at', regex=True)
df_step_count['start_time'] = pd.to_datetime(df_step_count['start_time'], dayfirst=True)
df_step_count['end_time'] = pd.to_datetime(df_step_count['end_time'], dayfirst=True)

In [80]:
step_by_day, step_day_keys = df_by_day(df_step_count)

In [81]:
step_by_day[step_day_keys[0]]

,speed,count,start_time,calorie,end_time,distance
1,1.388889,16,2021-11-28 13:50:00,0.570000,2021-11-28 13:50:00,11.510000
2,1.497405,22,2021-11-28 13:51:00,0.730000,2021-11-28 13:51:00,17.090000
3,1.277778,17,2021-11-28 13:56:00,0.590000,2021-11-28 13:56:00,12.440000
4,2.027778,19,2021-11-28 14:06:00,0.660000,2021-11-28 14:06:00,15.370000
5,1.277778,15,2021-11-28 14:11:00,0.520000,2021-11-28 14:11:00,11.120000
6,1.527778,59,2021-11-28 14:12:00,2.050000,2021-11-28 14:12:00,45.690000
7,1.764286,14,2021-11-28 14:12:00,0.457786,2021-11-28 14:12:00,12.350000
8,0.403583,20,2021-11-28 14:45:00,1.058468,2021-11-28 14:45:00,13.360000
9,1.388889,12,2021-11-28 14:45:00,0.400000,2021-11-28 14:45:00,9.020000
10,1.135878,15,2021-11-28 18:45:00,0.670492,2021-11-28 18:45:00,13.950000
11,0.964906,10,2021-11-28 18:46:00,0.452860,2021-11-28 18:46:00,8.850000
12,1.059598,17,2021-11-28 19:02:00,0.533953,2021-11-28 19:02:00,11.313921
13,0.656646,27,2021-11-28 19:03:00,1.047782,2021-11-28 19:03:00,17.346079
14,1.307898,23,2021-11-28 19:04:00,0.921975,2021-11-28 19:04:00,19.690001
15,1.839353,34,2021-11-28 19:05:00,1.259797,2021-11-28 19:05:00,30.219999
16,0.750778,19,2021-11-28 19:07:00,0.953889,2021-11-28 19:07:00,16.740000
17,1.410841,94,2021-11-28 19:17:00,3.370155,2021-11-28 19:17:00,73.741257
18,1.555556,33,2021-11-28 17:05:00,1.140000,2021-11-28 17:05:00,25.200000
19,2.444444,24,2021-11-28 18:22:00,0.790000,2021-11-28 18:22:00,19.780000
20,1.472222,18,2021-11-28 18:45:00,0.620000,2021-11-28 18:45:00,13.400000
21,1.694444,62,2021-11-28 19:02:00,2.100000,2021-11-28 19:02:00,47.670000
22,1.340409,67,2021-11-28 19:03:00,2.220000,2021-11-28 19:03:00,50.460000
23,1.277778,28,2021-11-28 19:04:00,0.930000,2021-11-28 19:04:00,20.680000
24,1.638889,28,2021-11-28 19:05:00,0.940000,2021-11-28 19:05:00,22.170000
25,1.361111,38,2021-11-28 19:06:00,1.290000,2021-11-28 19:06:00,29.660000
26,1.638889,41,2021-11-28 19:07:00,1.350000,2021-11-28 19:07:00,31.650000
27,1.533333,120,2021-11-28 19:17:00,4.000000,2021-11-28 19:17:00,92.000000
28,1.331915,50,2021-11-28 19:18:00,1.680630,2021-11-28 19:18:00,37.270210
29,1.278641,76,2021-11-28 19:19:00,2.723138,2021-11-28 19:19:00,57.838535
30,1.370881,29,2021-11-28 19:20:00,1.143215,2021-11-28 19:20:00,25.040001
31,0.682435,10,2021-11-28 20:12:00,0.329100,2021-11-28 20:12:00,5.721341
32,0.968972,1,2021-11-28 20:13:00,0.000000,2021-11-28 20:13:00,0.218659
33,0.944377,17,2021-11-28 20:17:00,0.446855,2021-11-28 20:17:00,9.180000
34,0.905863,13,2021-11-28 20:28:00,0.435590,2021-11-28 20:28:00,8.450000
35,0.978459,25,2021-11-28 20:29:00,0.913649,2021-11-28 20:29:00,17.853125
36,1.085649,86,2021-11-28 20:30:00,3.037548,2021-11-28 20:30:00,61.240479
37,1.376043,86,2021-11-28 20:31:00,2.992947,2021-11-28 20:31:00,64.747330
38,1.202710,33,2021-11-28 20:32:00,1.102882,2021-11-28 20:32:00,23.559065
39,1.599139,16,2021-11-28 20:43:00,0.567443,2021-11-28 20:43:00,13.930000
40,1.410540,56,2021-11-28 19:18:00,1.930000,2021-11-28 19:18:00,42.840000
41,1.361111,74,2021-11-28 19:19:00,2.620000,2021-11-28 19:19:00,55.530000
42,1.370497,54,2021-11-28 19:20:00,1.900000,2021-11-28 19:20:00,40.470000
43,1.416667,7,2021-11-28 19:22:00,0.240000,2021-11-28 19:22:00,5.390000
44,1.527778,18,2021-11-28 19:40:00,0.610000,2021-11-28 19:40:00,13.550000
45,2.504554,15,2021-11-28 20:07:00,0.520000,2021-11-28 20:07:00,12.570000
46,1.364239,36,2021-11-28 20:27:00,1.240000,2021-11-28 20:27:00,27.050000
47,1.388889,18,2021-11-28 20:28:00,0.660000,2021-11-28 20:28:00,13.760000
48,1.333333,30,2021-11-28 20:29:00,1.090000,2021-11-28 20:29:00,23.260000
49,1.417410,80,2021-11-28 20:30:00,2.680000,2021-11-28 20:30:00,61.330000
50,1.350456,93,2021-11-28 20:31:00,3.430000,2021-11-28 20:31:00,69.690000
51,1.416667,37,2021-11-28 20:32:00,1.220000,2021-11-28 20:32:00,28.340000
52,2.222222,24,2021-11-28 20:44:00,0.840000,2021-11-28 20:44:00,19.560000
53,1.602091,41,2021-11-28 20:45:00,1.410000,2021-11-28 20:45:00,31.430000
54,0.587370,11,2021-11-28 20:44:00,0.456574,2021-11-28 20:44:00,7.310000
57,1.305556,19,2021-11-28 23:34:00,0.670000,2021-11-28 23:34:00,13.820000
58,1.306241,35,2021-11-28 23:38:00,1.220000,2021-11-28 23:38:00,25.200000
59,1.682294,60,2021-11-28 23:39:00,2.050000,2021-11-28 23:39:00,47.080000
60,1.722222,3,2021-11-28 23:40:00,0.100000,2021-11-28 23:40:00,2.400000

# Use-case : 4 days ago (24.11.2021)
As we did not have data for the heart rate then, we will use the data we have from today, and pretend it was taken on that day. As this is merely an example, we will look at it during a day, but the analysis can easily be repeated fro a week, or larger period.

##### Get key for day we want

In [98]:
def get_key(day, month, year):
    for key in cal_day_keys:
        if key.start_time.month == day and key.start_time.day == month and key.start_time.year == year:
            cal_key = key
    return cal_key

In [99]:
day = 5
month = 12
year = 2021

day_key = get_key(day, month, year)

##### Filter calendar data to keep only data for a day

In [100]:
df_filtered_dates = cal_by_day[day_key]
# Create mask for bars in plotting
df_filtered_dates['plot_dummies'] = np.ones(len(df_filtered_dates)).astype(int)*df_heart_rate_json['heart_rate_max'].max()
#df_filtered_dates.at[893,'Title']= "Repas avec Flo Ã  Morges" 

df_filtered_dates['bar_width'] = df_filtered_dates['end_time'] - df_filtered_dates['start_time']
df_filtered_dates['bar_width'] = df_filtered_dates['bar_width'].apply(lambda t : t.seconds//3600 * 0.0415)

In [101]:
df_filtered_dates.head()

,Title,start_time,end_time,plot_dummies,bar_width
496,Midi avec Julia,2021-05-12 12:00:00,2021-05-12 14:00:00,167,0.0830
497,Appel Pidoux,2021-05-12 15:00:00,2021-05-12 16:00:00,167,0.0415

##### Prepare weather data for plotting

In [ ]:
# Weather data
actual_temp = []
feels_like_temp = []
weather = []

for i in range(len(weather_four_days_ago)):
    actual_temp.append(weather_four_days_ago[i].temperature('celsius')['temp'])
    feels_like_temp.append(weather_four_days_ago[i].temperature('celsius')['feels_like'])
    weather.append(weather_four_days_ago[i].detailed_status)

In [ ]:
data_range = pd.date_range(start=datetime(year_to_keep, month_to_keep, day_to_keep, 0, 0, 0), periods=24, freq="60 min")

# Create datafram
weather_data = [actual_temp, feels_like_temp, weather]
df_weather = pd.DataFrame(np.vstack(weather_data))
df_weather = df_weather.T
df_weather = df_weather.rename(columns={0:'actual_temp', 1:'feels_like_temp', 2: 'weather'})
df_weather['time'] = data_range

df_weather['actual_temp'] = df_weather['actual_temp'].astype(float)
df_weather['feels_like_temp'] = df_weather['feels_like_temp'].astype(float)

In [ ]:
df_weather.head(50)

##### Change day (cheating on day of heart rate measurement)

In [ ]:
offset = date.today().day - day_to_keep - 2
df_heart_rate_json['start_time'] = df_heart_rate_json['start_time'].apply(lambda t : t.replace(day=day_to_keep, month=month_to_keep, year=year_to_keep))
df_heart_rate_json['end_time'] = df_heart_rate_json['end_time'].apply(lambda t : t.replace(day=day_to_keep, month=month_to_keep, year=year_to_keep))

In [ ]:
df_heart_rate_json.head()

##### Prepare step count data

# Plotting all together

In [ ]:
import matplotlib.dates as mdates
fig, ax = plt.subplots(figsize=(20, 10))

# Plot Hear rate data
hr = ax.plot(df_heart_rate_json['start_time'],
        df_heart_rate_json['heart_rate'],
        color='purple', label='Heart Rate')

#accel = ax.plot(df_accel['time'], df_accel['Vector Magnitude'])


# Set bar plots style for events
cal = ax.bar(df_filtered_dates['start_time'],
        df_filtered_dates['plot_dummies'],
        color='green', width=df_filtered_dates['bar_width'], alpha=0.2, label='Calendar events', align='edge')
ax.bar_label(cal, labels=df_filtered_dates['Title'], label_type='center', rotation=90, weight='bold', fontsize=20)

# Format dates as hours:minutes
xformatter = mdates.DateFormatter('%H:%M')
plt.gcf().axes[0].xaxis.set_major_formatter(xformatter)


# Set title and labels for axes
ax.set_xlabel("Time of the day", fontsize=20)

ax.set_ylabel("Heart Rate", color="purple", fontsize=20)

# Create format for plotting temperature
#ax2=ax.twinx()

#Remove the night for purposes of plotting
df_weather_loc = df_weather.copy()
df_weather_loc = df_weather_loc.drop(range(13))

#ax2.plot(df_weather_loc['time'], df_weather_loc['actual_temp'], color='red', label='Actual Temperature')
#ax2.set_ylabel("Temperature (celsisus)")

# Ading legends
#ax.legend(bbox_to_anchor=(0.985, 1), prop={"size":20})


ax2=ax.twinx()
ax2.plot(df_accel['time'], df_accel['Vector Magnitude'], label="Accelerometer")

#ax2.legend("Accelerometer", prop={"size":20})
#ax.legend("Hear rate", prop={"size":20})
ax.set_ylabel("Heart Rate", color="purple", fontsize=20)
ax2.set_ylabel("Accelerometer", color="blue", fontsize=20)

ax.tick_params(axis='both', which='major', labelsize=20)
ax.tick_params(axis='both', which='minor', labelsize=8)

ax2.tick_params(axis='both', which='major', labelsize=20)
ax2.tick_params(axis='both', which='minor', labelsize=8)

# Ading legends
# bbox_to_anchor=(0.985, 1), 
ax.legend(prop={"size":20})
# bbox_to_anchor=(0.999, 0.93),
ax2.legend(bbox_to_anchor=(0.9835, 0.88), prop={"size":20})

#sns.set()
plt.savefig("images/cal_events_correlation.png", transparent=True)

In [ ]:
import matplotlib.dates as mdates
fig, ax = plt.subplots(figsize=(20, 10))

#Remove the night for purposes of plotting
df_weather_loc = df_weather.copy()
df_weather_loc = df_weather_loc.drop(range(13))

# Set bar plots style for events
weather = ax.bar(df_weather_loc['time'],
        df_weather_loc['actual_temp'],
        color='orange', width=0.03, alpha=0.2, label='Weather status')
ax.bar_label(weather, labels=df_weather_loc['weather'], label_type='center', rotation=90, weight='bold', fontsize=20)

# Format dates as hours:minutes
xformatter = mdates.DateFormatter('%H:%M')
plt.gcf().axes[0].xaxis.set_major_formatter(xformatter)


# Set title and labels for axes
ax.set_xlabel("Time of the day", fontsize=20)
ax.set_ylabel("Temperature (celsius)", color="orange", fontsize=20)
# Create format for plotting temperature
ax2=ax.twinx()


# Plot Hear rate data
ax2.plot(df_heart_rate_json['start_time'],
        df_heart_rate_json['heart_rate'],
        color='purple', label='Heart Rate')
#ax2.plot(df_weather_loc['time'], df_weather_loc['actual_temp'], color='red', label='Actual Temperature')
ax2.set_ylabel("Heart rate", color="purple", fontsize=20)

# Ading legends
# bbox_to_anchor=(0.985, 1), 
ax.legend(prop={"size":20})
# bbox_to_anchor=(0.999, 0.93),
ax2.legend(bbox_to_anchor=(0.999, 0.93), prop={"size":20})

ax.tick_params(axis='both', which='major', labelsize=20)
ax.tick_params(axis='both', which='minor', labelsize=8)

ax2.tick_params(axis='both', which='major', labelsize=20)
ax2.tick_params(axis='both', which='minor', labelsize=8)

# Display plot
plt.savefig("images/weather_events_correlation.png", transparent=True)
plt.show()